server:
  port: 8080
#  url的前缀
  servlet:
    context-path: /sell
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sell?characterEncoding=utf-8&useSSL=false
    password: 123456
    username: root
    driver-class-name: com.mysql.jdbc.Driver


  jpa:
#   显示sql语句
    show-sql: true

#    表更新
    hibernate:
      ddl-auto: update

#if 返回的值是null 就不返回
  jackson:
    default-property-inclusion: non_null